#!/bin/bash

ROOT_DIR=$(cd $(dirname $(dirname $0)) && pwd)

pushd $ROOT_DIR
bosh create-env vm.yml \
  -o ./infrastructures/virtualbox.yml \
  --vars-store creds.yml \
  --state state.json \
  -v internal_cidr=192.168.100.0/24 \
  -v internal_gw=192.168.100.1 \
  -v public_ip=192.168.100.4
popd
